name: CI
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  pull_request:
    branches:
    - master

jobs:
  validate-token-meta:
    name: Validate token meta json
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main
    - name: Checkout tokens-file-validator
      uses: actions/checkout@v4
      with:
        repository: InjectiveLabs/token-meta-validator
        ref: master
        token: ${{ secrets.GH_PAT }}
        path: validator
    - name: Setup Go ^1.21
      uses: actions/setup-go@v4
      with:
        go-version: '^1.21.6'
    - name: Install and build
      run: |
        cd validator
        go install .
    - name: Validate
      run: |
        cd main
        token-meta-validator --token-file=./pkg/token/token_meta.json
