name: CI
defaults:
  run:
    shell: bash -ieo pipefail {0}
on:
  pull_request:
    branches:
    - master

jobs:
  run-unittests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tokens-file-validator
      uses: actions/checkout@v4
      with:
        repository: github.com/InjectiveLabs/token-meta-validator
    - name: Setup Go ^1.21
      uses: actions/setup-go@v4
      with:
        go-version: '^1.21.6'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./... -o validate
    - name: Validate
      run: validate ./pkg/token/token_meta.json
